name: bandit
version: 1.8.3
summary: A Python security linter from PyCQA
description: |
  Bandit is a tool designed to find common security issues in Python
  code. To do this Bandit processes each file, builds an AST from it, and
  runs appropriate plugins against the AST nodes. Once Bandit has finished
  scanning all the files it generates a report.

base: core24
grade: stable
confinement: strict

apps:
  bandit:
    command: bin/bandit
    environment:
      PYTHONIOENCODING: utf-8
    plugs:
      - home

parts:
  bandit:
    plugin: python
    source: https://github.com/PyCQA/bandit.git
    source-tag: $CRAFT_PROJECT_VERSION
    stage:
      # avoid snapcraft trying to stage two copies of these same pieces by
      # removing them from the bandit part and keeping them from
      # bandit-sarif-exporter part below instead
      - -pyvenv.cfg
      - -bin/activate*
      - -lib/python3.12/site-packages/_distutils_hack/*
      - -lib/python3.12/site-packages/pbr*/*
      - -lib/python3.12/site-packages/pip*/*
      - -lib/python3.12/site-packages/pkg_resources*/*
      - -lib/python3.12/site-packages/setuptools*/*
      - -lib/python3.12/site-packages/wheel*/*

  bandit-sarif-formatter:
    after: [ bandit ]
    plugin: python
    source: https://github.com/microsoft/bandit-sarif-formatter.git
    source-tag: 1.1.1

